<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Add a new attachment' => '',
  'Are you sure you want to delete this node?' => '',
  'Attachment deleted.' => '',
  'Attachments' => '',
  'Available tags' => '',
  'Body' => '',
  'Breadcrumb' => '',
  'Content' => '',
  'Created' => '',
  'Delete' => '',
  'Deleted' => '',
  'Extension' => '',
  'Filename' => '',
  'Heading' => '',
  'Id' => '',
  'Locale' => '',
  'Meta Description' => '',
  'Meta Keywords' => '',
  'Meta Title' => '',
  'Mime Type' => '',
  'Name' => '',
  'No attachments found.' => '',
  'No parent' => '',
  'Node' => '',
  'Node deleted.' => '',
  'Node name cannot be changed.' => '',
  'Node updated.' => '',
  'Page Title' => '',
  'Page settings' => '',
  'Parent' => '',
  'Please note that the fields below are only used with pages.' => '',
  'Save' => '',
  'Size (bytes)' => '',
  'Stylesheet' => '',
  'Tag' => '',
  'URL' => '',
  'Update' => '',
  'Update :name' => '',
  'Updated' => '',
  'You are not allowed to access this page.' => '',
  'creates a link to an attached file' => '',
  'creates a mailto link' => '',
  'creates an external link' => '',
  'creates an internal link' => '',
  'displays an attached image' => '',
  'displays an inline node' => '',
  'displays the page heading' => '',
);
