<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'About' => '',
  'Admin panel' => '',
  'Alert Pay' => '',
  'Amount' => '',
  'Bonus' => '',
  'Compounding' => '',
  'Contact' => '',
  'Date' => '',
  'Deposit' => '',
  'Description' => '',
  'E-currency' => '',
  'Earning' => '',
  'Edit profile' => '',
  'Feedback' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Go to member area >>' => '',
  'History' => '',
  'Home' => '',
  'ID' => '',
  'Investment' => '',
  'Invite your friends and get referral commission to your account!' => '',
  'Liberty Reserve' => '',
  'Login' => '',
  'Logout ({username})' => '',
  'MMM2011-AUTO.COM' => '',
  'Max' => '',
  'Member' => '',
  'Messages' => '',
  'Min' => '',
  'Monfri' => '',
  'Monitor' => '',
  'Name' => '',
  'Penalty' => '',
  'Percent' => '',
  'Percent Per' => '',
  'Perfect Money' => '',
  'Periodicity' => '',
  'Periodicity value' => '',
  'Plan' => '',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => '',
  'Principal Back' => '',
  'Profile has been saved.' => '',
  'Promote yourself' => '',
  'Public' => '',
  'Rates' => '',
  'Register' => '',
  'Registration' => '',
  'Security' => '',
  'Status' => '',
  'Submit' => '',
  'Term' => '',
  'Term value' => '',
  'Transaction status' => '',
  'Type' => '',
  'User' => '',
  'Verification Code' => '',
  'Withdrawal' => '',
  'You referral link' => '',
  'Your payment has been failed!' => '',
  'Your payment has been successfully accepted!' => '',
  'day(s)' => '',
  'hour(s)' => '',
  'month(s)' => '',
  'week(s)' => '',
  'year(s)' => '',
);
