<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '<span class="red">Attention!</span> In this field you must specify the account
					details (bank account, an account in a payment system, credit card number, etc.), on which the funds
					will be transferred.' => '',
  '<span class="red">Attention!</span> To pay for a purchase you will be redirected to
			    the processing center. The amount specified
			    in the purchase of Russian rubles. For payment you can use any currency, which will be offered to the
			    processing center and will be automatically converted into Russian rubles.' => '',
  'Amount' => '',
  'Amount is too big!' => '',
  'Amount is too small!' => '',
  'Buy' => '',
  'Buy MAVRO' => '',
  'Buy rate (roubles)' => '',
  'Buying MAVRO {amount}' => '',
  'Confirm' => '',
  'ID' => '',
  'Member' => '',
  'Must be greater than 0!' => '',
  'Operation\'s history' => '',
  'Payment info' => '',
  'Pending' => '',
  'Processed' => '',
  'Quantity of MAVRO' => '',
  'Sell' => '',
  'Sell MAVRO' => '',
  'Sell rate (roubles)' => '',
  'Status' => '',
  'Time' => '',
  'Total amount (roubles)' => '',
  'Type' => '',
  'We change the world!' => '',
  'You have' => '',
  'You have {mavro} MAVRO' => '',
  'You sell' => '',
  'Your sell request has been accepted. It will be executed in 24 hours.' => '',
);
