<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account summary' => '',
  'Address' => '',
  'Alternative question answer' => '',
  'Alternative security question' => '',
  'Answer' => '',
  'Birthdate' => '',
  'City' => '',
  'Country' => '',
  'Daily Limit' => '',
  'Date Registered' => '',
  'E-currency' => '',
  'E-currency purse' => '',
  'E-mail address' => '',
  'Edit profile' => '',
  'Firstname' => '',
  'Hash' => '',
  'History' => '',
  'ID' => '',
  'Invalid date format!' => '',
  'Invalid security question!' => '',
  'Lastname' => '',
  'Login' => '',
  'Login Notify' => '',
  'Login Pin' => '',
  'Login Pin must be of 5 digits.' => '',
  'Login must be at least 3 symbols!' => '',
  'Make deposit' => '',
  'Master Pin' => '',
  'Master Pin must be of 3 digits.' => '',
  'Member area' => '',
  'Messages' => '',
  'Monitor' => '',
  'Must differ to "Security question"!' => '',
  'Password' => '',
  'Password must be at least 6 symbols!' => '',
  'Profile Notify' => '',
  'Promotion' => '',
  'Repeat password' => '',
  'Request withdrawal' => '',
  'Security question' => '',
  'Status' => '',
  'Total Limit' => '',
  'Transaction Limit' => '',
  'Withdrawal Notify' => '',
  'Your language' => '',
  'Zip' => '',
  'Login Pin must be of 3 digits.' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
);
