<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'About' => 'О проекте',
  'Address' => '',
  'Admin panel' => 'Администрирование',
  'Alert Pay' => '',
  'Alternative question answer' => '',
  'Alternative security question' => '',
  'Answer' => '',
  'Birthdate' => '',
  'City' => '',
  'Contact' => 'Контакты',
  'Country' => 'Страна',
  'Daily Limit' => '',
  'Date Registered' => '',
  'E-currency' => '',
  'E-currency purse' => '',
  'E-mail address' => '',
  'Firstname' => '',
  'Hash' => '',
  'Home' => 'Главная',
  'ID' => '',
  'Invalid date format!' => '',
  'Invalid security question!' => '',
  'Lastname' => '',
  'Liberty Reserve' => '',
  'Login' => 'Вход',
  'Login Notify' => '',
  'Login Pin' => '',
  'Login Pin must be of 3 digits.' => '',
  'Login Pin must be of 5 digits.' => '',
  'Login must be at least 3 symbols!' => '',
  'Logout ({username})' => 'Выход ({username})',
  'Master Pin' => '',
  'Member' => 'Личный кабинет',
  'Monitor' => '',
  'Must differ to "Security question"!' => '',
  'Password' => '',
  'Password must be at least 3 symbols!' => '',
  'Perfect Money' => '',
  'Profile Notify' => '',
  'Register' => 'Регистрация',
  'Registration' => '',
  'Repeat password' => '',
  'Security' => '',
  'Security question' => '',
  'Status' => 'Статус',
  'Total Limit' => '',
  'Transaction Limit' => '',
  'Withdrawal Notify' => '',
  'You have successfully create an account! You can use your credentials to log in.' => '',
  'Your language' => '',
  'Zip' => '',
);
