<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account summary' => '',
  'Address' => '',
  'Alert Pay' => '',
  'Alternative question answer' => '',
  'Alternative security question' => '',
  'Answer' => '',
  'Birthdate' => '',
  'Bonus' => '',
  'City' => '',
  'Compounding' => '',
  'Daily Limit' => '',
  'Date' => '',
  'Date Registered' => '',
  'Deposit' => '',
  'Description' => '',
  'E-currency' => '',
  'E-currency purse' => '',
  'E-mail address' => '',
  'Earning' => '',
  'Edit profile' => '',
  'Firstname' => '',
  'Hash' => '',
  'History' => '',
  'ID' => '',
  'Invalid date format!' => '',
  'Invalid security question!' => '',
  'Investment' => '',
  'Invite your friends and get referral commission to your account!' => '',
  'Lastname' => '',
  'Liberty Reserve' => '',
  'Login Notify' => '',
  'Login Pin' => '',
  'Login Pin must be of 3 digits.' => '',
  'Login Pin must be of 5 digits.' => '',
  'Login must be at least 3 symbols!' => '',
  'Login pin' => '',
  'Make deposit' => '',
  'Master Pin' => '',
  'Max' => '',
  'Messages' => '',
  'Min' => '',
  'Monfri' => '',
  'Monitor' => '',
  'Must differ to "Security question"!' => '',
  'Name' => '',
  'Password' => '',
  'Password must be at least 6 symbols!' => '',
  'Penalty' => '',
  'Percent' => '',
  'Percent Per' => '',
  'Perfect Money' => '',
  'Periodicity' => '',
  'Principal Back' => '',
  'Profile Notify' => '',
  'Profile has been saved.' => '',
  'Promote yourself' => '',
  'Promotion' => '',
  'Public' => '',
  'Registration' => '',
  'Remember me next time' => '',
  'Repeat password' => '',
  'Request withdrawal' => '',
  'Security' => '',
  'Security question' => '',
  'Term' => '',
  'Total Limit' => '',
  'Transaction Limit' => '',
  'Type' => '',
  'User' => '',
  'Username' => '',
  'Withdrawal' => '',
  'Withdrawal Notify' => '',
  'You have successfully create an account! You can use your credentials to log in.' => '',
  'You referral link' => '',
  'Your language' => '',
  'Zip' => '',
  'Password must be at least 3 symbols!' => '@@@@',
  'About' => 'О проекте',
  'Admin panel' => 'Администрирование',
  'Contact' => 'Контакты',
  'Country' => 'Страна',
  'Home' => 'Главная',
  'Login' => 'Вход',
  'Logout ({username})' => 'Выход ({username})',
  'Member' => 'Личный кабинет',
  'Register' => 'Регистрация',
  'Status' => 'Статус',
);
