<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account summary' => '',
  'Alert Pay' => '',
  'Amount' => '',
  'Bonus' => '',
  'Compounding' => '',
  'Date' => '',
  'Deposit' => '',
  'Description' => '',
  'E-currency' => '',
  'Earning' => '',
  'Edit profile' => '',
  'History' => '',
  'ID' => '',
  'Investment' => '',
  'Invite your friends and get referral commission to your account!' => '',
  'Liberty Reserve' => '',
  'Login pin' => '',
  'Make deposit' => '',
  'Max' => '',
  'Member area' => '',
  'Messages' => '',
  'Min' => '',
  'Monfri' => '',
  'Monitor' => '',
  'Name' => '',
  'Password' => '',
  'Penalty' => '',
  'Percent' => '',
  'Percent Per' => '',
  'Perfect Money' => '',
  'Periodicity' => '',
  'Periodicity value' => '',
  'Plan' => '',
  'Principal Back' => '',
  'Profile has been saved.' => '',
  'Promote yourself' => '',
  'Promotion' => '',
  'Public' => '',
  'Rates' => '',
  'Registration' => '',
  'Remember me next time' => '',
  'Request withdrawal' => '',
  'Security' => '',
  'Term' => '',
  'Term value' => '',
  'Type' => '',
  'User' => '',
  'Username' => '',
  'Withdrawal' => '',
  'You have successfully create an account! You can use your credentials to log in.' => '',
  'You referral link' => '',
  'day(s)' => 'день',
  'hour(s)' => 'час',
  'month(s)' => 'месяц',
  'week(s)' => 'неделя',
  'year(s)' => 'год',
  'About' => 'О проекте',
  'Admin panel' => 'Администрирование',
  'Contact' => 'Контакты',
  'Home' => 'Главная',
  'Login' => 'Вход',
  'Logout ({username})' => 'Выход ({username})',
  'Member' => 'Личный кабинет',
  'Register' => 'Регистрация',
  'Status' => 'Статус',
);
