<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Hash' => '',
  'History' => 'История',
  'ID' => '',
  'Request withdrawal' => 'Вывод средств',
  'Account summary' => 'Мой счет',
  'Address' => 'Адрес',
  'Alternative question answer' => 'Ответ на альтернативный секретный вопрос',
  'Alternative security question' => 'Альтернативный секретный вопрос',
  'Answer' => 'Ответ',
  'Birthdate' => 'Дата рожения',
  'City' => 'Город',
  'Country' => 'Страна',
  'Daily Limit' => 'Дневной лимит',
  'Date Registered' => 'Дата регистрации',
  'E-currency' => 'Электронная валюта',
  'E-currency purse' => 'Кошелек',
  'E-mail address' => 'Адрес электронной почты',
  'Edit profile' => 'Редактировать профиль',
  'Firstname' => 'Имя',
  'Invalid date format!' => 'Неправильный формат даты!',
  'Invalid security question!' => 'Неправильный секретный вопрос!',
  'Lastname' => 'Фамилия',
  'Login' => 'Имя пользователя',
  'Login Notify' => 'Вход в систему',
  'Login Pin' => 'PIN на вход',
  'Login Pin must be of 5 digits.' => 'PIN должен состоять из 5 цифр.',
  'Login must be at least 3 symbols!' => 'Имя пользователя должно состоять минимум из 3 символов!',
  'Make deposit' => 'Сделать вклад',
  'Master Pin' => 'Мастер PIN',
  'Master Pin must be of 3 digits.' => 'PIN должен состоять из 3 цифр.',
  'Member area' => 'Личный кабинет',
  'Messages' => 'Сообщения',
  'Monitor' => 'Монитор',
  'Must differ to "Security question"!' => 'Вопрос должен отличаться от первого секретного вопроса!',
  'Password' => 'Пароль',
  'Password must be at least 6 symbols!' => 'Пароль должен состоять минимум 6 символов!',
  'Profile Notify' => 'Изменение профиля',
  'Promotion' => 'Реклама',
  'Repeat password' => 'Повторить пароль',
  'Security question' => 'Секретный вопрос',
  'Status' => 'Статус',
  'Total Limit' => 'Общий лимит',
  'Transaction Limit' => 'Лимит на транзакцию',
  'Withdrawal Notify' => 'Вывод средств',
  'Your language' => 'Язык',
  'Zip' => 'Индекс',
);
