<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '"route" or "loc" options must be set.' => '',
  'Alias is not directory or file. Alias: \'{alias}\'' => '',
  'Alias path not founded. Alias: \'{alias}\'' => '',
  'Aliases elements must be set as string or an array.' => '',
  'Cache configuration must be set as array.' => '',
  'Controllers aliases is not set.' => '',
  'Error occured while trying to eval() model expression. Expression was: {value}' => '',
  'Main sitemap file (sitemap.xml) must have configuration.' => '',
  'Option \'{key}\' cannot be empty.' => '',
  'Reflection extension is required.' => '',
  'SimpleXML extension is required.' => '',
  'Sitemap defaults must be set as an array.' => '',
  'Sitemap file configuration must be set as an array.' => '',
  'Sitemap file not founded or disabled.' => '',
  'SitemapGenerator error: {error}' => '',
  'Sitemaps configuration must be set as an array.' => '',
  'Sitemaps must be set as array. Current value: {value}' => '',
  'Sitemaps quantity limit per sitemap-index file exceeded.' => '',
  'Specified cache component not founed. Cache ID: {value}' => '',
  'URLs quantity limit per sitemap file exceeded.' => '',
  'Unable to format datetime object. Datetime value: {value}' => '',
  'Unable to parse given datetime. Error: {error}' => '',
  'Url changefreq must be set as string. Current value: {value}' => '',
  'Url lastmod must be set as string. Current value: {value}' => '',
  'Url loc must be set as string. Current value: {value}' => '',
  'Url parameters must be set as array. Current value: {value}' => '',
  'Url route must be set as string. Current value: {value}' => '',
  'Zlib extension must be enabled.' => '',
);
