<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'E-currency and other' => 'Электронные валюты и другое',
  '3 digits.' => '3 цифры',
  '5 digits.' => '5 цифр',
  'Format: YYYY-MM-DD (Ex: {example})' => 'Формат: ГГГГ-ММ-ДД (Пример: {example})',
  'Minimum 3 symbols of digits and letters.' => 'Минимум 3 символа (цифры и буквы).',
  'Minimum 6 symbols.' => 'Минимум 6 символов.',
  'Must differ to "Security question".' => 'Должен отличаться от "Секретного вопроса".',
  'Valid e-mail address.' => 'Действующий адрес электронной почты.',
  'You have successfully create an account! You can use your credentials to log in.' => 'Поздравляем! Вы успешно зарегистрировались и теперь можете войти в личный кабинет.',
);
