<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Cache configuration must be set as array.' => 'Конфигурация кеширования должна быть задана в виде массива.',
  '"route" or "loc" options must be set.' => 'Должны быть установлены \'route\' или \'loc\' параметры.',
  'Alias is not directory or file. Alias: \'{alias}\'' => 'Алиас не указывает на директорию или файл. Алиас: \'{alias}\'',
  'Alias path not founded. Alias: \'{alias}\'' => 'Путь алиаса не найден. Алиас: \'{alias}\'',
  'Aliases elements must be set as string or an array.' => 'Алиасы должны быть заданы в форме массива или строки',
  'Controllers aliases is not set.' => 'Не заданы алиасы контроллеров для поиска ссылок.',
  'Error occured while trying to eval() model expression. Expression was: {value}' => 'Произошла ошибка eval() функции для выражения модели. Выражение: {value}',
  'Main sitemap file (sitemap.xml) must have configuration.' => 'Главный sitemap.xml файл должен иметь конфигурацию.',
  'Option \'{key}\' cannot be empty.' => 'Параметр \'{key}\' не может быть пустым.',
  'Reflection extension is required.' => 'Необходим модуль Reflection.',
  'SimpleXML extension is required.' => 'Необходим модуль SimpleXML.',
  'Sitemap defaults must be set as an array.' => 'Параметры по-умолчанию для sitemap должны быть заданы в виде массива.',
  'Sitemap file configuration must be set as an array.' => 'Конфигурация sitemap файла должна быть задана в виде массива.',
  'Sitemap file not founded or disabled.' => 'Sitemap файл не найден или отключен.',
  'SitemapGenerator error: {error}' => 'Ошибка SitemapGenerator: {error}',
  'Sitemaps configuration must be set as an array.' => 'Конфигурация sitemap файла должна быть задана в виде массив.',
  'Sitemaps must be set as array. Current value: {value}' => 'Sitemap элементы должны быть заданы в виде массива. Текущее значение: {value}',
  'Sitemaps quantity limit per sitemap-index file exceeded.' => 'Превышен лимит sitemap файлов для sitemap-index файла.',
  'Specified cache component not founed. Cache ID: {value}' => 'Указанный cache компонент не найден.',
  'URLs quantity limit per sitemap file exceeded.' => 'Превышен лимит числа ссылок на один sitemap файл.',
  'Unable to format datetime object. Datetime value: {value}' => 'Неудалась форматирование datetime::format(). Значение даты: {value}',
  'Unable to parse given datetime. Error: {error}' => 'Неудалась конвертация даты в формат W3C. Ошибка: {error}',
  'Url changefreq must be set as string. Current value: {value}' => 'Параметр changefreq должен быть задан в форме строки. Текущее значение: {value}',
  'Url lastmod must be set as string. Current value: {value}' => 'Параметр changefreq должен быть задан в форме строки. Текущее значение: {value}',
  'Url loc must be set as string. Current value: {value}' => 'Параметр loc должен быть задан в форме строки. Текущее значение: {value}',
  'Url parameters must be set as array. Current value: {value}' => 'Параметры URL должны быть заданы в форме массива. Текущее значение: {value}',
  'Url route must be set as string. Current value: {value}' => 'Параметр route должен быть задан в форме строки. Текущее значение: {value}',
  'Zlib extension must be enabled.' => 'Необходим модуль Zlib.',
);
